### PR TITLE
Select color for leds and pattern in Web-UI

### PR DESCRIPTION
**Pull request by con-f-use**
Make the Web-UI for ws2812 a little more useful. Still buggy and needs testing but I'm too tired now and too busy next week.
### Features
- Users can enter one or many ranges of LEDs, e.g. 1-4,7,20,25,72-103 and select a color for them
- Users can select a pattern, that is displayed continuously (even when not connected to the Web-UI) until a color is selected or data is sent over UDP

demo
### Bugs
- Some patterns don't work to well yet. Most prominently numbers >17 (the default theme). Should be a timing issues with the `frames` variable. Didn't really pay attention there, sorry.
### ToDo:
- Implement a "neutral" color, that just leaves the old color. Currently all led in the entered range are turned off. They should stay as they were. Probably requires an `if` in `ws2812.c`. A "leave as is" color could be useful elsewhere, too.
- Test this in different browsers. I managed to transfer binary data over the Web-UI, but I'm not sure how robust the transfer is, especially cross-platform.
- The pattern number should be stored in flash and be loaded on boot (saved on change), so the esp can operate autonomously, once a pattern is set
- Maybe move the UI around a bit, e.g. color picker next to "Set Color" button etc.

@cnlohr : I would very much like for you to test and improve this. I feel like the timing-stuff could be handled better, but I don't know anything about the esp8266's timers. I'm hesitant to merge it yet,

### CODE REVIEW

**Comment by cnlohr** [comment]
This control is super unintuitive for making specific colors, but, I got your new timer thing in and it works much better.  Now operates at about 100 hz.  Now that I'm thinking about that, that's a little high.  Will change that.

**Comment by cnlohr** [comment]
Werid, this didn't show up in the merge tree.  Perhaps I did things wrong.  I took your thing, made a new branch, made changes, then merged it into main.  Can I commit things locally to your branch then merge your branch in the future/

**Comment by cnlohr** [comment]
We should consider a parameter system like in ColorChord, maybe embedding it into esp82xx, maybe allowing arbitrary string parameters, too... so we could make strings that describe the behavior of what the LEDs do, then just store it as a parameter...  That way, whenever this thing wakes up, it becomes an automatic ESP8266-make-color-ws-do-things thing.

**Comment by con-f-use** [comment]
> This control is super unintuitive for making specific colors

Huh? There is a regular old browser-builtin color picker to the left of "Pattern/Range". You select the color there, then enter the LED range, than press "Set Color". Ranges just work like specifying pages on a print. "Page one to five, ten and twentyone, please!" It was the best mix of easy and general that came to my mind.

> so we could make strings that describe the behavior of what the LEDs do, then just store it as a parameter

I was thinking about that, too. The thing is, I don't want to design a time-series coloring language and write a parser for it. It would also need some math-functions, if you're serious about it. At that point you could just use a lua interpreter. As cool as it would be, it goes beyond the scope, of what I'm willing to do for a bunch of blinking lights. Maybe somebody has done it already, and in C (slim chance)?

Maybe just write C code, and load it dynamically via the swtich-case in `pattern.c`? But that would require the user to have the xtensa compiler ready. I don't really see a very  good solution.

How would you go about for a "change nothing" color, like `#000001` is just skipped in `ws2812_push(...)`?

**Comment by cnlohr** [comment]
Re: Color selection.  Yes, to light up specific colors is easy, but, what if I want 1-4 yellow, 5-8 red and 9-12 blue?   Or is that not an intended use code?

Re: other thing.  No. Nevermind let's run away from something that crazy.

**Comment by con-f-use** [comment]
I was thinking a three step process:
- Enter 1-4, select yellow, click (just the leds 1-4 change, the rest stays colored as is)
- Enter 5-8, select red, click (just 5-8 change, while esp. 1-4 stay yellow)
- Enter 9-12, select blue, click (...)

That (among other use cases) is why I wanted to have a "change nothing" color.

But one could of course change the javascript to accept something like below:

```
1-4#ffff00,5-8#ff0000,9-12#0000ff
```

I.e. an optional color behind the range. That would be a really easy change, considering each color for each led is send by the websocket, just like `top`/`wsend` would send them. Should be something like this, for the relevant lines in `main.js`:

``` javascript
var val = $('#LEDSelect').val();
if( ! val.match(/^\d+(-\d+(#[0-9a-fA-F]{6,6})?)?(,\d+(-\d+(#[0-9a-fA-F]{6,6})?)?)*$/) ) {
    $('#LEDSelect').css( "background-color", "#ff0000");
    return false;
}
$('#LEDSelect').css( "background-color", "#ffffff");
var numLEDs = parseInt( $('#LEDNum').val() );
var toks = val.split(',');
var leds = new Array();
var color = document.getElementById('LEDColor').value;
color = color.replace('#','');
for(var i=0; i<toks.length; ++i) {
    var colsplt = toks[i].split("#");
    var rangesplt = colsplt[0].split("-");
    if( colsplt.length > 1 ) color = colsplit[1];
    if( rangesplt.length < 2 ) {
        var idx = parseInt(rangesplt[0]);
        if(idx<=numLEDs) leds[idx] = color;
    } else {
        var min = parseInt(rangesplt[0]);
        var max = parseInt(rangesplt[1]);
        if( min > max ) { var tmp=min; min=max; max=tmp; }
        for(var j=min; j<=max && j<=numLEDs; ++j)
            leds[j] = color;
    }
}
```

 Still I'd like to have a "transparency" / "do not change" color.

**Comment by con-f-use** [comment]
Any good location to store a bit of config data such as the pattern in flash?

**Comment by cnlohr** [comment]
So, it's a little unorganized right now, but in the SETTINGS variable.  You'll see a user data section.

**Comment by con-f-use** [comment]
Thanks, that helped alot. Changes are pushed.

What about the "don't change" color?

**Comment by cnlohr** [comment]
Perhaps include "Alpha" instead #bbggrr , do #aabbggrr where if it's 00 it does not effect, ff full effect.

**Comment by con-f-use** [comment]
It's more a question on how to implement it on the firmware side of things. Entries will have to be skipped, when the "don't change" color comes up in `ws2812_push` or something. Need a closer look at the function. At first glance it's hard so see.

_Edit_: Nevermind, I forgot, both the Web-UI (`data` in `GotLED(...)`) and the frimware (`last_leds[]`) know all LED colors. But a byte sequence for leaving an LED unchanged by `ws2812_push(...)`, i.e. skipping a buffer entry might be more elegant.

**Pull request merged**
