### PR TITLE
Add 'pattern' argument in wsend'

### PR DESCRIPTION
**Pull request by con-f-use**
Also improve Readme and Makefiles and bump to latest esp82xx revision. 

Btw. I renamed `top` into `wssend` sind you send data to the ws2812s...

### CODE REVIEW

**Comment by cnlohr** [comment]
1) It's not showing me if there's any differences in wsend and top.  Are they the same other than name?

2) What is WS_SLEEP?

**Comment by con-f-use** [comment]
1) No, I made a few small changes, i.e. the switch statement. You can now specify the light pattern as an integer argument.

2) `WS_SLEEP` specifies the wait time between sends with `wsend` (former `top`).

Simply found it useful to have different patterns available from command line and adjust their speed.

**Comment by cnlohr** [comment]
Did you test it?  If so, we shall merge away.

**Comment by con-f-use** [comment]
By all means. It is tested.

**Comment by con-f-use** [comment]
Did I get an invitation here and decline it accidentally? Got some weird e-mails from github...

**Comment by cnlohr** [comment]
I accidentally un-made you a collaborator and re-made you a collaborator.  You will have to reaccept.

**Comment by con-f-use** [comment]
Nice, thanks for your trust!

**Pull request merged**
