### PR TITLE
Fix generation of scripts used in index.html

### PR DESCRIPTION
**Pull request by ricardomv**
I was having issues with loading the page because `{{PAGE_JQUERYFL}}` doesn't get updated during build. This patch removes it because `PAGE_SCRIPTS` seems to do the same thing.

Offtopic: do you know why i had to change the `PAGE_OFFSET` to 1048576?

### CODE REVIEW

**Comment by cnlohr** [comment]
I do not know why.  I have noticed issues with that recently though with newer SDKs.  I am thinking about now, most people have 2MB+ flashes so it shouldn't be an issue.

Would you mind doing a pull request to esp82xx as well with this?

**Comment by ricardomv** [comment]
@cnlohr sorry, i didn't understand what you mean with the PR whit this? the change in this PR or the `PAGE_OFFSET` issue. If you meant this PR it doesn't really apply because this is how it's done there.

**Comment by cnlohr** [comment]
PR?  PAGE_OFFSET determines where the MPFS is stored.  If 65536, it will have limited use.  If 1MB, it will only work on 2MB+ devices.

**Comment by ricardomv** [comment]
PR=>PullRequest

**Comment by cnlohr** [comment]
(1) My comment was about PAGE_OFFSET, not about this PR (it was about your P.S.)

(2) This pull request where you fix the javascript on webpage thing... That can be applied to esp82xx.  esp82xx is the right place to put the fix.

**Comment by ricardomv** [comment]
(1) i got that

(2) esp82xx is fine. the variable `PAGE_SCRIPTS` is correctly defined in `user.cfg.example` that is used in the Makefile. I think the confusion is with the variable `PAGE_SCRIPT` (without the S) used in the html file.

**Comment by cnlohr** [comment]
OH! Cool.  Thanks!

**Pull request merged**
