### PR TITLE
Improve makefile

### PR DESCRIPTION
**Pull request by bbusse**
Remove hard-coded path / refactor path handling, add .gitignore

### CODE REVIEW

**Comment by cnlohr** [comment]
Gaah.  I just noticed this now.  I can't figure out how to view the changes you've made.  People have requested I attach my bins and elfs, so I typically do that.  But, I would love to see the changes you've made to the makefile.

**Comment by jnsat** [comment]
Can't you just click on a commit, like Makefile: refactor paths ->
https://github.com/bbusse/esp8266ws2812i2s/commit/6bd0b2c4e20777d92b35786a8f8b8cf7b7ab6621

**Comment by cnlohr** [comment]
I believe this is already OBE, as it says that it's got conflicts. I will do that in the future.  In the mean time, I have a note to manually implement some of this this weekend.

**Comment by gdamjan** [comment]
it's better to attach binaries on the github releases page. 
basically, just go to https://github.com/cnlohr/esp8266ws2812i2s/releases and make a tag, which will make a release, and then you can just upload the binary there.

that way you don't pollute the source code repository with binaries.

**Comment by cnlohr** [comment]
I will consider doing that in the future, however, I usually do only upload binaries whenever I have anything more than a minor fix.  There are other projects where that would make much more sense.

**Comment by cnlohr** [comment]
This branch is now OBE with @con-f-use 's new build system.

**Pull request closed without merging**
